version: "3.6"

services:
  db:
    image: postgres:11.6
    # https://docs.docker.com/compose/compose-file/#expose
    expose:
      - "5432"
    ports:
      - "2222:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "changelog_dev"
    # https://docs.docker.com/compose/compose-file/#volumes
    # volumes:
    #   - postgres:/var/lib/postgresql/data
    #   - ./priv:/app/priv
  app:
    # Keep this in lock-step with docker/Dockerfile.production
    image: gcr.io/df-infrastructure/thechangelog
    # command: bash -exec "cd /app && mix deps.get && ( if (mix deps | grep 'mix deps.compile' 1>/dev/null); then mix deps.compile; fi ) && (cd assets && yarn install) && mix do ecto.create, ecto.migrate, phx.server"
    build:
      context: .
      dockerfile: Dockerfile.production
    environment:
      DB_URL: "ecto://postgres:postgres@db:5432/changelog_dev"
      VIRTUAL_HOST: &host "${HOST:-localhost}"
      HOST: *host
    # https://docs.docker.com/compose/compose-file/#ports
    ports:
      - "4000:4000"
    # volumes:
    #   - ./:/app
    depends_on:
      - db
  adminer:
    image: adminer
    # https://docs.docker.com/compose/compose-file/#expose
    expose:
      - "8080"
    ports:
      - "9000:8080"
    depends_on:
      - db

volumes:
  postgres:
